language: cpp

#cache: 
#  directories:
#    - /opt/fairsoft/nov15p1

env:

  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "t65xtdQ7WpWBujB04gE7Ezh9cZ/GtHFEnwJyHeZdFDLeM0YgcNg8+Iv0LQj40DCbfMLV7c0lDV9hKOqfn+OhtHzBHglaiyHwMRZREH0VoIEnK/0W1z4nDFe0z5uv0SCp1UkhsnotDTiR99OzENg525SfTEiO5n9tdlz0gDCA40M="

    - ROOT_VERSION=root5
    - ROOT_VERSION=root6

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
    exclude:
        - os: osx
          compiler: gcc
        - os: linux
          compiler: clang


addons:
  coverity_scan:

    # GitHub project metadata
    # ** specific to your project **
    project:
      name: FairRootGroup/FairRoot
      version: dev
      description: "dev branch"

    # Where email notification of build analysis results will be sent
    notification_email: f.uhlig@gsi.de

    # Commands to prepare for build_command
    # ** likely specific to your build **
    build_command_prepend: 'make build && cd build && export SIMPATH=/opt/fairsoft/\${FAIRSOFT_VERSION} && cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc ..'

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty

before_install:
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        sudo apt-get update -q;
        sudo apt-get install -y cmake cmake-data g++ gcc gfortran build-essential make patch sed 
                                libx11-dev libxft-dev libxext-dev libxpm-dev libxmu-dev libglu1-mesa-dev libgl1-mesa-dev 
                                ncurses-dev libcurl4-openssl-dev curl bzip2 gzip unzip tar subversion git xutils-dev flex 
                                bison lsb-release python-dev libc6-dev-i386 libxml2-dev wget libssl-dev 
                                automake autoconf libtool;
        wget http://fairroot.gsi.de/downloads/fairsoft-nov15p1-${ROOT_VERSION}_1.0_amd64.deb;
        sudo dpkg -i fairsoft-nov15p1-${ROOT_VERSION}_1.0_amd64.deb;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        brew update;
        brew install openssl;
        brew uninstall gcc;
        brew install gcc;
        curl -L -O http://fairroot.gsi.de/downloads/fairsoft_nov15p2_${ROOT_VERSION}-1.0.pkg;
        sudo installer -pkg ./fairsoft_nov15p2_${ROOT_VERSION}-1.0.pkg -target /;
      fi

install:

before_script:
    - $CXX --version
    - cmake --version
    - if test "$TRAVIS_OS_NAME" = "linux"; then
        echo "export LINUX_FLAVOUR=Ubuntu14.04" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=g++;-DCMAKE_C_COMPILER=gcc\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=nov15p1_\${ROOT_VERSION}" >> Dart.cfg;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx"; then
        echo "export LINUX_FLAVOUR=MacOSX10.9.5" > Dart.cfg;
        echo "export EXTRA_FLAGS=\"-DCMAKE_CXX_COMPILER=clang++;-DCMAKE_C_COMPILER=clang\" " >> Dart.cfg;
        echo "export FAIRSOFT_VERSION=nov15p2_\${ROOT_VERSION}" >> Dart.cfg;
      fi
    - echo "export GIT_BRANCH=\${TRAVIS_COMMIT}" >> Dart.cfg
    - echo "export SIMPATH=/opt/fairsoft/\${FAIRSOFT_VERSION}" >> Dart.cfg; 
    - echo "export BUILDDIR=/tmp/fairroot/build_fairroot_\${FAIRSOFT_VERSION}" >> Dart.cfg
    - echo "export SOURCEDIR=$PWD" >> Dart.cfg
    - echo "export SITE=\"Travis CI\" " >> Dart.cfg
    - echo $PWD
    - cat Dart.cfg

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then
        ./Dart.sh Experimental Dart.cfg;
      fi   

notifications:
  email:
    recipients:
      - m.al-turany@gsi.de
      - f.uhlig@gsi.de
    on_success: always
    on_failure: always
